### ISSUE TITLE
new feature request : xml output

### ISSUE THREAD

**Issue by macdoor** [sid5432/pyOTDR#1]
please add xml file output option. xml is more post processing friendly

**Comment by sid5432** [comment]
Interesting thought.  I'll try to get to it in the next few weeks (but no promises!).

**Comment by macdoor** [comment]
great! I also made some modifications by myself. I tried to use lazyxml to dump xml. like this
` print >>logfile, lazyxml.dumps(results, cdata=False, indent=' ' * 4, root='sor')`
But I encountered a serious problem, There are whitespaces in xml tags. 
`  <build condition>BC (as-built)</build condition>`
So I can not get valid xml output.

**Comment by sid5432** [comment]
Good solution using lazyxml.  To fix the whitespace problem, I have added short function to substitute all the problematic characters with an underscore ('_') character.
