### ISSUE TITLE
pyotdr command not found error in linux

### ISSUE THREAD

**Issue by vivindeveloper** [sid5432/pyOTDR#10]
vivin@vivin-X540SAA:~/Downloads/pyOTDR-master/data$ ls
demo_ab-dump.json  M200_Sample_005_S13-dump.json  sample1310_lowDR.sor
demo_ab-dump.xml   M200_Sample_005_S13.sor        sample1310_lowDR-trace.dat
demo_ab.sor        M200_Sample_005_S13-trace.dat
demo_ab-trace.dat  sample1310_lowDR-dump.json
vivin@vivin-X540SAA:~/Downloads/pyOTDR-master/data$ pyotdr.py demo_ab.sor
pyotdr.py: command not found

I am not able to parse this demo file in linux. any suggestions tp what is the issue

**Comment by sid5432** [comment]
It looks like you are in the "data" folder, while the pyotdr.py program is in the folder above; that is why it is reporting "command not found".  Try this (in the "data" folder):

**../pyotdr.py demo_ab.sor**

or if you are in the Download/pyOTDR-master/ folder, do

**./pyotdr.py data/demo_ab.sor**

**Comment by vivindeveloper** [comment]
Thanks!!!
