### ISSUE TITLE
Port to Python3

### ISSUE THREAD

**Issue by RemiDesgrange** [sid5432/pyOTDR#14]
Since pyOTDR now use lazyxml, it cannot be used in python3. Also could add type hinting into the process.

**Comment by sid5432** [comment]
I have been able to get lazyxml (1.2.1) with pip in python 3.7.6; not sure why you say it cannot be used?

**Comment by RemiDesgrange** [comment]
Ok I tested with python 3.8. Will investigate.

**Comment by RemiDesgrange** [comment]
Since you merge my PR #7 I'll now be able to add github actions with tox to test pyOTDR on multiple version of python :tada: :-)

**Comment by sid5432** [comment]
I use pyenv for multiple versions of python. lazyxml also runs in 3.8.1, and the tests pass. But there is a warning that encoding that is going away in python 3.9, so that needs to be fixed.

**Comment by RemiDesgrange** [comment]
I also use pyenv. I'll rework my PR. You revert it with gitea, which does not revert it in github hum, didn't see it. No problem tought.

**Comment by sid5432** [comment]
Sorry for the mess (I need to get better at managing this). About lazyxml: I vaguely remember that at one time there was a dependency on the "utils" module (that you need to install it first) that was not explicitly called in lazyxml requirements. But it's been a while, and I have always installed "utils" first, so I do not know if that it still true (or was it ever true?).

**Comment by RemiDesgrange** [comment]
It's still true, you need to install `utils` first. You cannot do `pip install -r requirements.txt` it'll fail. That's why I replace lazyxml with dicttoxml in my PR. Also LazyXML is unmaintained.
