### ISSUE TITLE
porting pyOTDR to PHP class

### ISSUE THREAD

**Issue by scramatte** [sid5432/pyOTDR#30]
Hello,

I need to port pyOTDR to PHP class.
Anybody is able to achieve it ? 

If somebody is interested in , please contact me to discuss details ...

Regards

**Comment by RemiDesgrange** [comment]
Hi. I coded a really simple server https://github.com/RemiDesgrange/BalanceTonSor which takes a SOR file as input and gives you a json back, it uses pyOTDR. It can be a "temporary" solution to your problem.
