### ISSUE TITLE
Can we edit a .sor file ?

### ISSUE THREAD

**Issue by Mglt-b** [sid5432/pyOTDR#32]
Hello

there is a way to edit a .sor file ?

location A / B, cable_ID .. etc ?

Thanks

**Comment by sid5432** [comment]
Editing a .SOR file is messy. It is a binary format, so you need to get a binary (or hexadecimal) editor. But the bigger problem is there are offsets encoded into the file, so unless you are replacing the strings with exactly the same number of bytes, inserting or removing bytes means that you will need to adjust all the down-stream offsets.

A few years ago somebody asked about this (with my Perl version, also under my sid5432 GitHub account), to change the cable ID. I wrote a simply program called **change_fiberid.pl** that does that. You might want to have a look at that. But I don't have anything readily available (in either the Python or the Perl version) that allows you to also change location data.

**Comment by Mglt-b** [comment]
Hello,

Thank you for the answer,
I carry out fiber optic deployments in France, and sometimes the data entered during the processing of OTDR measurements are false (origin, end, cable name, pulse length, thresholds, etc.)

I was looking for a way not to go back to the field and take these measurements again, a little bit of cheating.

But according to your answer, I am too limited in Python / development knowledge to succeed in such a program

thank you

**Comment by OSHI7** [comment]
Related question :Is there any hope to decode the proprietary data block?

**Comment by RemiDesgrange** [comment]
@Mglt-b I already wrote code to detect wrong sor file and detect wrong thresold (in a France FTTH context)

@OSHI7 if you can provide us some SOR files + the proprietary data (decode via viavi soft or other) then yes.

**Comment by RemiDesgrange** [comment]
@Mglt-b I am not on Windows, but this software seems to modify sor file: http://www.gazlan.ru/ (part of the source are on github).
