### ISSUE TITLE
Marker data

### ISSUE THREAD

**Issue by Dalk1** [sid5432/pyOTDR#42]
I just started experimenting with pyOTDR, but is it possible to pull the marker data? LSA attenuation and 2 points section attenuation between the markers set in the OTDR machine?

**Comment by RemiDesgrange** [comment]
* Can you provide an example SOR file?
* By marker data you mean? Markers data are present in the `KeyEvent` section or the resulting json/XML.
* you need to computed 2 point section attenuation by yourself. pyOTDR doesn't compute anything, it just translates the binary SOR file into json/xml. Maybe this can be achieved with jq easily (never tried).

**Comment by RemiDesgrange** [comment]
Closing since no response has been added.
